### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by qianglise** [axil/numpy-data-types#1]
Hi Lev,
thanks for the nice article. 
Under what license is this material and [the previous post](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d) provided, please?

**Comment by axil** [comment]
Hi Qianglise, 

'[A Comprehensive Guide to NumPy Data Types](https://betterprogramming.pub/a-comprehensive-guide-to-numpy-data-types-8f62cb57ea83?sk=a417246f0cf9e24aca734525711299d3)' is licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)
'[NumPy Illustrated: The Visual Guide to NumPy](https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d?sk=57b908a77aa44075a49293fa1631dd9b)' is 'All rights reserved'.

Thanks and regards,
Lev

**Comment by qianglise** [comment]
Thanks for the info.

Best
qianglise
